import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "./AuthProvider";
import { LanguageProvider } from "../components/LanguageProvider";
import { NotificationProvider } from "../components/NotificationProvider";
import { AutoTranslationProvider } from "../components/AutoTranslationProvider";
import AutoTranslator from "../components/AutoTranslator";
import ChunkLoadErrorHandler from "../components/ChunkLoadErrorHandler";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LanguageProvider>
          <AutoTranslationProvider>
            <AuthProvider>
              <NotificationProvider>
                <ChunkLoadErrorHandler />
                <AutoTranslator />
                {children}
              </NotificationProvider>
            </AuthProvider>
          </AutoTranslationProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
